### ISSUE TITLE
Add Import Vignette

### ISSUE THREAD

**Issue by gabrielodom** [RaymondBalise/tidyREDCap#21]
We need a vignette that shows the 3 data import strategies:

- using tidyREDCap (new function `import_instrument_[redcapr]()`)
- using `redcapAPI::`
- using `REDCapR::`

Also, all vignettes should be updated to point users to this vignette (instead of the current calls in each vignette to `redcapAPI::`)

**Comment by gabrielodom** [comment]
We actually have an import vignette, written by Lauren ages ago. Anna will take over and continue working on this

**Comment by RaymondBalise** [comment]
done
