### ISSUE TITLE
make_choose_all_table not working without variable labels

### ISSUE THREAD

**Issue by wdefreitas** [RaymondBalise/tidyREDCap#36]
If people manually export from REDCap using the stock r script exports with ".factor" variables, the variables are missing labels that prevent make_choose_all_table from working as expected. 

1. Add an attribute check to the function.
2. Return a meaningful error, if there is no label.                         

Add a function to label ".factor" variables

**Comment by RaymondBalise** [comment]
The API export addresses this.  If we get requests from people who can't use the API we will address.

**Comment by RaymondBalise** [comment]
Instructions were added in the 1.2 vignette.
