### ISSUE TITLE
make_choose_all_table sorting by multiple instances per case

### ISSUE THREAD

**Issue by drstormR** [RaymondBalise/tidyREDCap#45]
It would be great to have a function in make_choose_all_table, to clearly see how many patients have multiple entries, as with the current table you get a count of all the ticked boxes, but not sorted by how many patients have multiple ticked boxes.

**Comment by RaymondBalise** [comment]
Thanks for writing @drstormR. I want to make sure I understand your request. 

Take a look at the [make_binary_word()](https://raymondbalise.github.io/tidyREDCap/articles/makeBinaryWord.html) function. It shows the pattern of responses for people who check multiple boxes.  Does that help?  

Would you like a function that counts the **total number** of boxes checked (for a choose all that apply question)?

**Comment by drstormR** [comment]
Yeah, that helps. Thanks.  I can make it work with the make_binary_word() function. 

Thanks a lot.

**Comment by RaymondBalise** [comment]
Sounds good.  We are always looking for ideas to make it easier to work with REDCap data in R.  So, please let us know when you run into tasks that make you think "there must be an easier way."
