### ISSUE TITLE
adapt for REDCapR 1.2.0

### ISSUE THREAD

**Issue by wibeasley** [RaymondBalise/tidyREDCap#59]
https://github.com/OuhscBbmc/REDCapR/issues/479

The upcoming version of `REDCapR::redcap_read()` returns a tibble instead of data.frame.  I've adjusted a few places.

**Comment by RaymondBalise** [comment]
Thank you so much for working on this!  I would love to have you walk me though one of the changes.   I will ping Gabriel and see if he has any time this week.
