### ISSUE TITLE
Automatically split a project into tables

### ISSUE THREAD

**Issue by RaymondBalise** [RaymondBalise/tidyREDCap#7]
Add function that uses the metadata to automatically split the output in tables based on the instrument.

**Comment by RaymondBalise** [comment]
I accidentally worked on this on main... @gabrielodom It would be good if you could give it the once over before I push.

**Comment by RaymondBalise** [comment]
Wayne and I worked and we integrated some of my code into his.

**Comment by gabrielodom** [comment]
Thank you. My kid is sick, and I haven't had any time for this.
